import Utils from '../helper/utils';
/**
 * A basic player.
 * Should only be generated by the PlayerBuilder
 */
export class Player {
    private playerId: number;
    private playerName: string = "unnamed";

    constructor(name: string, id: number) {
        this.playerName = name;
        this.playerId = id;
    }

    public getPlayerId() {
        return this.playerId;
    }

    public getPlayerName() {
        return this.playerName;
    }

    public setPlayerName(newName: string) {
        console.log("setPlayerName() from: " + this.playerName + "to: " + newName);
        this.playerName = newName;
        return this;
    }
}
